name: Deploy Notebooks to Databricks

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/*'

jobs:
  deploy-notebook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Changed Notebooks
      id: changes
      run: |
        # Get a list of changed notebooks
        notebooks=$(git diff-tree --no-commit-id --name-only -r HEAD..origin/master | grep '^notebooks/')
        echo "Changed notebooks: $notebooks"
        echo "::set-output name=notebooks::$notebooks"

    - name: Deploy Notebooks
      if: steps.changes.outputs.notebooks != ''
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        IFS=' ' read -r -a notebook_array <<< "${{ steps.changes.outputs.notebooks }}"
        for notebook in "${notebook_array[@]}"
        do
          echo "Deploying $notebook to Databricks"
          notebook_name=$(basename "$notebook")
          curl -n -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" \
          $DATABRICKS_HOST/api/2.0/workspace/import \
          -F path="/Workspace/stackgenius/dev/$notebook_name" \
          -F content=@$notebook \
          -F language=SQL \
          -F format=SOURCE \
          -F overwrite=true
        done
